development: &default
  adapter: postgresql
  encoding: utf8
  pool: 2

development:
  <<: *default
  database: appointment-fair_development

test:
  <<: *default
  database: appointment-fair_test

production:
  <<: *default
  database: appointment-fair_production
  username: appointment-fair
  password: <%= ENV['APPOINTMENT-FAIR_DATABASE_PASSWORD'] %>
